### PR TITLE
Merged the SSJ repository and split the DesmoJ realization into a separate feature.

### PR DESCRIPTION
**Pull request by sdkrach**

### CODE REVIEW

**Review by seiferma — CHANGES_REQUESTED** [review]
The build works for me and the resulting update site looks good. A few minor change requests:
* delete folder releng/org.palladiosimulator.simucomssj.updatesite because it is not used anymore
* delete folder bundles/de.uka.ipd.sdq.simulation.abstractsimengine.example because it does not contain any valueable content

A more important question that comes to my mind is if this change breaks users of AbstractSimEngine. Before your change `de.uka.ipd.sdq.simulation.abstractsimengine.feature` did include the desmoj plugin. This is not the case anymore. We, however, have multiple users of this feature. In order to keep the product working, we have to include at least one additional feature (desmoj / ssj) in the product. In addition, is there any documentation that we should update regarding the installation of the additional feature?

**Comment by sdkrach** [comment]
You are right. The two folders are useless. Furthermore, I will adapt the product accordingly (I'd stick with our current default DesmoJ).

To my knowledge, there is no specific documentation on which features need to be installed from the aggregated updatesite in case of a manual installation.

**Review by seiferma — APPROVED** [review]

**Comment by snowball77** [comment]
As SSJ used to be GPL, we never shipped it as default (In fact, strictly, we are only allowed to ship the pluging without the SSJ jar).

**Comment by seiferma** [comment]
@snowball77 The latest SSJ is licensed under Apache2. Therefore, we can ship it together with EPL code now. After this change, there is no real default anymore because you can install the DesmoJ or the SSJ feature or both of them. However, we will stick with DesmoJ in the product as @sdkrach said.

**Comment by snowball77** [comment]
Ok, maybe it would be nice to promote the SSJ plugin then more again as it is significantly faster... :)

**Pull request merged**
